export const START_LOADING = 'START_LOADING';
export const SET_LOADED = 'SET_LOADED';
export const SET_ERROR = 'SET_ERROR';
export const FINISH_LOADING = 'FINISH_LOADING';

export const HISTORY_LOCATION = 'HISTORY_LOCATION';
